### PR TITLE
Add NGL viewer as bokeh extension

### PR DESCRIPTION
**Pull request by Jhsmit**
This is a draft PR to address #15

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Thanks @Jhsmit . This is very much appreciated. 

Is there anything in special in the implementation I should be aware of?
Is there anything in particular in your use case that needs to be supported by the widget?

When I should take a look please let me know. Thanks.

**Comment by Jhsmit** [comment]
Thanks, I'll try to make some time for this hopefully next week.

**Comment by MarcSkovMadsen** [comment]
@Jhsmit . I have a working version implemented. It’s just needs some docs.

but looking at what is possible i can see that multiple stages are possible. I don’t know if that ought to be supported and how?

**Comment by MarcSkovMadsen** [comment]
I’ve released this. It would helt s great deal if you tested it out @Jhsmit and let me know sjat Can be improviseret. Thanks

**Comment by Jhsmit** [comment]
Nice, I don't completely understand the implementation but it looks very clean. I've tested it briefly and it works well. 
I had some problems I'll see if they reproduce and make issues.

Multiple stages is probably for displaying multiple molecules/proteins in one view. 
This is usually very useful, for example for displaying multiple (related) proteins at the same time, but then would require full control over the position and rotation of both molecules in 3D space.

Is it OK if I use your implementation for my own work? (PyHDX)
Also,  I might want to adopt your project layout using invoke etc, if thats OK. I've seen it before, did you first implement this for panel-highcharts?

Finally, and this is probably pedantry, although NGL viewer can display small molecules (typically subject of chemistry), it is more often used for displaying large biomolecules such as proteins and DNA and would therefore be a better match for a panel-biochemistry package ;)

**Pull request merged**
