### PR TITLE
Adds Pbde Molstar

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Continuation of #19 

A Panel Pane to wrap the PDBe implementation of the Mol* ('MolStar') viewer.

Check out

- [PDBe Mol*](https://github.com/PDBeurope/pdbe-molstar)
- [Mol*](https://molstar.org/)
- [Mol* GitHub](https://github.com/molstar/molstar)

Cite Mol*:
David Sehnal, Sebastian Bittrich, Mandar Deshpande, Radka Svobodová, Karel Berka,
Václav Bazgier, Sameer Velankar, Stephen K Burley, Jaroslav Koča, Alexander S Rose:
Mol* Viewer: modern web app for 3D visualization and analysis of large biomolecular structures,
Nucleic Acids Research, 2021; https://doi.org/10.1093/nar/gkab314.

# Todo:

- [] Test that dynamic updates work
- [] Decide if `light` theme should be could `default` as is custom in Panel.
- [] Decide if default theme should be `dark` or `default`/ `light`.
- [] Add/ use utility functions
- [] Add events. 
- [] Fix that the component get slower and slower on each `rerender`.
- [] Reference Notebook
- [] Add automated tests
- [] Test, Test, Test
- [] pypi package
- [] conda package
- [] Communication
- 
## Nice to have

- Some Gallery notebook showing an example application. 
- Some way to update the `css` file across all PdbeMolstar instances when the theme changes.
- Set default theme based on `theme=default` or `them=dark` url query args.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
https://user-images.githubusercontent.com/42288570/147883741-25b67e5b-afa6-4fbd-9e65-4fb9c34cb0dc.mp4

I will leave it here @Jhsmit . Could you give it a spin and make a PR into this branch? Feel free to tell me if I should work on something to help.

**Comment by MarcSkovMadsen** [comment]
FYI. I've added you as a member of this repo and to the gitter channel @Jhsmit

**Comment by Jhsmit** [comment]
Thanks Marc, I'll have a look.

"make a PR into this branch?" , What do you mean by this? add commits to this PR or should I start from here and commit to my own fork and PR from there?

**Comment by MarcSkovMadsen** [comment]
What I mean is that It would be nice for me to see and accept changes to this branch. 

I would expect that has to be done via a separate pull request from your fork/ branch into this branch. But if there are other ways and you prefer them just use them.

If you know how to collaborate on a feature branch like this please let me know. Not so used to it :-)

**Comment by Jhsmit** [comment]
Ok yep I think i managed it in #21. 
Usually my workflow I just me in a lonely repo so I had to do some git-fu to figure it out.

**Comment by MarcSkovMadsen** [comment]
Another PR has been approved

**Comment by MarcSkovMadsen** [comment]
Not merged :-)

**Comment by MarcSkovMadsen** [comment]
I will approve this one now @Jhsmit . I believe its in a good enough state to release, and then we can improve later.

I plan to publish package and market it on twitter later today. Hope its ok?

**Comment by Jhsmit** [comment]
Thanks Marc!
Sounds good to me. Lets get it out and then we might solutions to the resizing / events later. 
I'll put it in PyHDX and also tweet about it later

**Comment by MarcSkovMadsen** [comment]
It will not be today. But ASAP. Something got in the way :-)

**Comment by MarcSkovMadsen** [comment]
- I've release v0.0.12 to pypi
- I've requested v0.0.12 release on conda-forge https://github.com/conda-forge/panel-chemistry-feedstock/pull/1

I've tested. But for some reason the Panel jupyter-preview and Panel apps are not working on binder.

- Preview: https://mybinder.org/v2/gh/marcskovmadsen/panel-chemistry/HEAD?urlpath=lab/tree/examples/reference/PDBe_MolStar.ipynb
- App: https://mybinder.org/v2/gh/marcskovmadsen/panel-chemistry/HEAD?urlpath=panel/PDBe_MolStar

**Comment by Jhsmit** [comment]
Both work fine for me:
image
I did have the issue where the resizing wasn't triggered correctly and only half of the viewer was showing. But re-executing the cell solved that. 

On conda-forge, you should merge the PR yourself if all checks pass since you're the maintainer.

**Comment by MarcSkovMadsen** [comment]
Hmm. I don't have a merge button. 

image

**Comment by Jhsmit** [comment]
I get this for the preview binding link you posted above:
image

All seems to work fine.

**Comment by Jhsmit** [comment]
Regarding conda-forge, its strange you do not have write access

Are you in the conda-forge/panel-chemistry team?
You should be able to find that on your github.com homepage in the bar on the left

This is what it looks like for me:
image

Perhaps you could try this procedure here:
https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

**Pull request merged**
